package com.nicta.provenance.pipeline;

/**
 * @author Trams Wang
 * @version 1.2
 * Date: Jan. 19, 2016
 *
 *   Representing the log line information that will be stored into ES server.
 */
public class LogLine {

    /**
     *   Source variable name in Pig Latin script. There maybe more than one variable used for processing. In such
     * cases, all variable names are separated by ','.
     * E.g. "v1,v2,v3";
     */
    public String srcvar;

    /**
     *   Index of the data that referred by srcvar. In cases where there are more than one variable used for processing,
     * all indices are also separated by ',' and should be one-to-one corresponding to those names in srcvar.
     */
    public String srcidx;

    /**
     *   Processing unit name that deal with srcvar and generate dstvar in Pig Latin script.
     */
    public String processor;

    /**
     *   Pig Latin script variable name that stores the result generated by above processing unit.
     */
    public String dstvar;

    /**
     *   Index of the data that referred by dstvar.
     */
    public String dstidx;

    /**
     *   Create an instance of LogLine and initiate all data members to null.
     */
    public LogLine()
    {
        srcvar = null;
        srcidx = null;
        processor = null;
        dstvar = null;
        dstidx = null;
    }
}
